### ISSUE TITLE
Product Backlog 

### ISSUE THREAD

**Issue by karinalieu** [alisalam5/ISDM-Team3#19]
Please add any user stories below to create our backlog.
Here's a good website if you are unclear on how to develop a product backlog:
https://www.lucidchart.com/blog/how-to-develop-a-product-backlog-in-agile

**Comment by karinalieu** [comment]
•	As a customer, I want to be personally matched to an appropriate RM based on their performance and product knowledge so that I will be able to obtain the highest-quality and most enjoyable travel experience.
•	As a RM, I want to build a profile and skill matrix through an initial questionnaire so that I will be able to better satisfy and serve customers more effectively and efficiently.
•	As a customer, I want to have a quick response when calling up the travel company so that I can be served effectively and efficiently.
•	As a RM, I want to serve customers with the highest purchase likelihood score first so that the chance of achieving a sale will increase.
•	As a customer, I want to be redirected to the first available appropriate RM during busy times so that I can be served effectively and efficiently.

**Comment by Kin-Shun-Jordan-Wong** [comment]
User stories:
- As a relationship manager, I want to create supporting tool so that I can match with certain customers that are best suitable to my specialised knowledge and skills.
- As a relationship manager, I want the system to generate significant guidelines and a script so that I can provide an improved service to the end-customer.
- As a relationship manager, I want the outbound call system to create a target list so that I can have a history of past products proposed and potential customers.
As a customer, I want to be served by the most suitable relationship manager based on my profile and interest so that I can gain a greater understanding of my desired holiday trip.
- As a customer, I want to be able to talk to an interactive voice response so that I can be directed to the appropriate and suitable relationship manager.

**Comment by alisalam5** [comment]
As an RM, I want to be matched customers that best suit the skills and knowledge I can provide so that I can provide the best customised service and secure sales. 

As a customer, I want to be provided a service that is knowledgeable towards my social and cultural needs so that I may find a suitable holiday packet.

As an RM, I want to build an accurate profile and skill matrix so that I will be directed to customers that most suit my skillset and knowledge. 

 As a customer calling the CMC, I want to be efficiently directed to an RM that  will be able to assist me with any enquiries so that I may resolve my issues in  a short timely manner.

As an RM, I want to be provided with an assisting tool (target list) so that I can improve my sales and service for new potential customers during outbound   calls. 

As a customer, I want to build a precise customer profile so that I can be  matched with an RM that suits my needs.

**Comment by Leng-Houston** [comment]
As a customer with a specific travel destination in mind, I want to speak with an RM that is well informed with that country so that my enquiries can be answered quickly and accurately.

As a customer with poor English, I want to speak with an RM that can communicate in my language so that I can understand the types of holiday packages offered.

As an RM I want to be matched with customers that are interested in travel destinations that I am familiar with so that I can provide the best possible service.

As an RM I want to know more about my customers so that I can provide a more suitable service.
